dist: bionic

language: go
go:
  - 1.13.x
env:
  global:
    - GO111MODULE=on
# Only clone the most recent commit.
git:
  depth: 1

# Skip the install step. Don't `go get` dependencies. Only build with the code
# in vendor/
install: true

script:
  - go mod vendor
  - export GIT_VERSION=$(git describe --tags --long --always)
  - GOOS=linux GOARCH=amd64 go build -mod vendor -ldflags "-X main.version=${GIT_VERSION}" -o build/vault-pki-exporter.linux-amd64 cmd/main.go
  - sha256sum build/vault-pki-exporter.linux-amd64 > build/vault-pki-exporter.linux-amd64.sha256sum

deploy:
  provider: releases
  api_key:
    secure: abizzh2+i8dZXDWxmp3bop2bu50GdkhjuGROy9X+nU2UZHWR7FWN9BF0FHoNMkv5sXipH/KJooPOaQCA4h3VXz772Isy5d+mDHAh/UQTC25WpN+orFcLfVFUExZKFl1FEmBZlNS7vMtLme6CjVC7Sa2a3Jk2eiuBPzfBnrmvLxpkAgxNcpg7AV2wloW5qwX9wwG+ZUZwlRgiNbWHGvcm9yjQJFFQASU2fj6lbHQHVKQZlWfdqo8pXAU15AhyAPw18u1lvNM4fMg1A+HY65QPqHbWNY50+6inlzS116Y6IrHjBvZa61ivEgRGc7XrAKXeKjSY8OZmj8IuyjqhGsRIIH3ALhG8ZkZxQIfXJ/0fOYS2wK2Tl9WvQA9+qldHE932Yk6xEDpbYBMjCUwCkh+aK9PiqQEo41X544VToAIuljlFxlPRhgXeNrtDyCYAl9ijbkTA0p7p6cSIRtDcialdPNykBo78dSTUy5DhCh+BYSCSOOU4Z4uBxKsqEX+kSBCZB872jOIRyq7hye3DnfKG4crNZsEcB6b1JRol/pA1Qr64rGTBDTC7yfMCoGH7OSEQQ0wvSTodvoCbWzy2Sy7oeE0FIpPW4JtfS5My2i1hg8/i/xi6rDpRfv2imuSb99S3O4TicTk6yg8z4Z5oavlmANdIBUFXFniTOxa0DdNuj6s=
  file: build/*
  skip_cleanup: true
  on:
    tags: true